[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_BLOCKCHAIN_NETWORK,NEXT_PUBLIC_BLOCKCHAIN_CHAIN_ID,NEXT_PUBLIC_BLOCKCHAIN_EXPLORER_URL,NEXT_PUBLIC_BACKEND_API_URL,NEXTAUTH_URL,NEXT_PUBLIC_CONTRACT_ADDRESS,NEXT_PUBLIC_BLOCKCHAIN_RPC_URL"
